### PR TITLE
feat: upgrade dependencies

### PR DESCRIPTION
**Pull request by popomore**
- use eslint-config-egg
- upgrade to mocha@3
- upgrade thenify

### CODE REVIEW

**Comment by popomore** [comment]
https://github.com/blakeembrey/co-mocha/pull/20

**Comment by popomore** [comment]
https://github.com/thunks/thunk-mocha/pull/2

**Comment by popomore** [comment]
https://github.com/thunks/thunk-mocha/pull/2

**Comment by popomore** [comment]
Use const, should bump major

**Comment by dead-horse** [comment]
+1

**Comment by dead-horse** [comment]
2.0.0

**Pull request merged**
